# Generated by Django 4.2.11 on 2024-04-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('TA', 'Ta'), ('Instructor', 'Instructor'), ('Supervisor', 'Supervisor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('section', models.IntegerField()),
                ('start', models.DateField(max_length=20)),
                ('end', models.DateField(max_length=20)),
                ('credits', models.IntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='ta_app.user')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='ta_app.user')),
            ],
        ),
    ]
