# Generated by Django 5.0.3 on 2024-05-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('Course_description', models.TextField(blank=True, max_length=500, null=True)),
                ('MeetType', models.CharField(choices=[('Online', 'Online'), ('In Person', 'Inperson'), ('Hybird', 'Hybird')], default='In Person', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('TA', 'Ta'), ('Instructor', 'Instructor'), ('Supervisor', 'Supervisor')], max_length=20)),
                ('java_skill', models.BooleanField(default=False)),
                ('python_skill', models.BooleanField(default=False)),
                ('frontend_skill', models.BooleanField(default=False)),
                ('backend_skill', models.BooleanField(default=False)),
                ('scala_skill', models.BooleanField(default=False)),
                ('discrete_math_skill', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField()),
                ('LecLab', models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab')], default='Lecture', max_length=20)),
                ('start', models.DateTimeField(max_length=20)),
                ('end', models.DateTimeField(max_length=20)),
                ('credits', models.IntegerField()),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='ta_app.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to='ta_app.user')),
                ('ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta', to='ta_app.user')),
            ],
        ),
    ]
