# Generated by Django 5.0.3 on 2024-05-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0002_remove_course_credits_remove_course_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
